#!/bin/bash
# This bash script runs all the magic_contribuion_XXXXX.txt files in $fileDir through make_magic_plots and puts the 
# output in the $plotDir and /var/www/html/plots with a directory labeled with the magic Id and copies the directory over to S3 for easy MagIC website access.
# program skips data files that are corrupted so they don't throw errors.

# These files can be moved where needed.
plotDir=/home/magic/contributions/batchPlots
#fileDir=/home/magic/contributions/afterVersion3 #If the length of this changes, change startIndex below
fileDir=/home/magic/contributions/afterV3Large0 #If the length of this changes, change startIndex below

echo Start:$(date)
for file in $fileDir/*
do
    echo $(date)
    startIndex=59 #number of chars in full fileDir name up to the _ at the start of the magic contribution number (value needed is the column number of the last _)
    echo startIndex is $startIndex
    endIndex=$(expr index $file .)  
    echo endIndex is $endIndex
    diffIndex=$(expr $endIndex - $startIndex - 1)
    echo diffIndex is $diffIndex
    newDir=${file:startIndex:diffIndex}

    if expr "$newDir" : "11821";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "11846";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "14019";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "14127";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "14290";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "14575";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "15417";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "15454";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "15454";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "15640";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "16273";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    elif expr "$newDir" : "16302";
    then
        echo PlotServer: MagIC contribution $file has bad data or formatting. Skipping.
    else
        echo newDir is $newDir
        rm -r $plotDir/$newDir
        mkdir $plotDir/$newDir
        cp $file $plotDir/$newDir
        cd $plotDir/$newDir
        pwd
        download_magic.py -f magic_contribution_$newDir.txt
        make_magic_plots.py
        mkdir ../tmp
        mv *.txt ../tmp
        cd ..
        aws s3 rm s3://magic-plots/$newDir/ --recursive
        aws s3 cp $newDir s3://magic-plots/$newDir --recursive
        mv tmp/* $newDir
        cp -r $newDir /var/www/html/plots/
        rmdir tmp
        echo $(date)
    fi
done
echo Done:$(date)

